
CREATE TABLE HOSPITALES (COD_Hospital int(10) NOT NULL AUTO_INCREMENT, NOMBRE varchar(255) NOT NULL UNIQUE, PRIMARY KEY (COD_Hospital));
CREATE TABLE GESTION_HOSPITALARIA (ID_HOSPITALIZACION int(11) NOT NULL AUTO_INCREMENT, TIPO_DOC_PACIENTE varchar(255) NOT NULL, FEC_INGRESO date NOT NULL, FEC_SALIDA date NOT NULL, FEC_CREACION date NOT NULL, HOSPITALESCOD_Hospital int(10) NOT NULL, PACIENTESNO_DOCUMENTO int(11) NOT NULL, PRIMARY KEY (ID_HOSPITALIZACION));
CREATE TABLE PACIENTES (NO_DOCUMENTO int(11) NOT NULL AUTO_INCREMENT, TIPO_DOCUMENTO varchar(255) NOT NULL, NOMBRES varchar(255) NOT NULL, APELLIDOS varchar(255) NOT NULL, FEC_NACIMIENTO date NOT NULL, EMAIL varchar(255) NOT NULL, PRIMARY KEY (NO_DOCUMENTO));
ALTER TABLE GESTION_HOSPITALARIA ADD INDEX FKGESTION_HO346617 (HOSPITALESCOD_Hospital), ADD CONSTRAINT FKGESTION_HO346617 FOREIGN KEY (HOSPITALESCOD_Hospital) REFERENCES HOSPITALES (COD_Hospital);
ALTER TABLE GESTION_HOSPITALARIA ADD INDEX FKGESTION_HO6805 (PACIENTESNO_DOCUMENTO), ADD CONSTRAINT FKGESTION_HO6805 FOREIGN KEY (PACIENTESNO_DOCUMENTO) REFERENCES PACIENTES (NO_DOCUMENTO);
